"""Offline metadata for default-feature Retok builds; requires Python 3.11+.

Cargo's target-filtered normal-edge closure includes proc-macro support crates.
For packed builds, cargo tree supplies feature-resolved normal/build edges;
cargo metadata alone unifies features across dev, host and target contexts.
Dev edges are excluded. Build-only edges of the vocabulary generator are
inventoried separately from the normal closure. Package hashes identify cached
.crate archives, not compiled object code. The caller supplies the build's source
commit and target; those assertions cannot be recovered from an arbitrary executable.

All license/notice files from each authenticated crate archive are copied in
full. The published tiktoken-rs crate lacks LICENSE, so a reviewed local copy
is required for legacy raw-vocabulary builds. Pinned GitHub BPE and libyaml
license supplements are included below. yaml-edit's explicit Apache-2.0 declaration
is paired with complete canonical Apache terms and source provenance.
A reviewed OpenAI/tiktoken MIT license is also required. Never substitute a
license identifier or a generated copyright for either MIT document.
The known winapi-x86_64-pc-windows-gnu 0.4.0 archive omits its licenses;
its supplement comes only from authenticated normal-parent winapi 0.3.9.

The reviewed runtime manifest is UTF-8 JSON, for example (replace placeholders):
{"target":"x86_64-unknown-linux-musl","components":[
  {"name":"rust-std","version":"EXACT_VERSION","source":"https://SOURCE",
   "license":"MIT OR Apache-2.0","sha256":"SOURCE_OR_INPUT_SHA256",
   "notices":[{"label":"Rust licenses","path":"rust-LICENSE.txt"}]},
  {"name":"musl","version":"EXACT_VERSION","source":"https://SOURCE",
   "license":"MIT","sha256":"SOURCE_OR_INPUT_SHA256",
   "notices":[{"label":"musl copyright","path":"musl-COPYRIGHT.txt"}]}
]}
Every target requires rust-std (including bundled Rust runtime support); musl
targets additionally require musl, and windows-gnu requires mingw-w64 and allows
an additional gcc-runtime component. No OS dynamic libraries are included.
Supply exact reviewed source/input hashes, not hashes of unrelated binaries.
Notice paths are absolute or relative to the manifest; labels are public.
Files must be complete reviewed UTF-8 texts, including all attributions.
Canonical manifest content is embedded in the SBOM with paths replaced by file
SHA256 hashes, components sorted by name, and notices sorted by label.
Review establishes license completeness and build provenance;
the tool verifies inventory, hashes, and copying without fetching anything.
"""

import gzip
import hashlib
import json
import mmap
from pathlib import Path
import re
import subprocess
import tarfile
import tomllib


VERSION = tomllib.loads(
    (Path(__file__).resolve().parent.parent / "Cargo.toml").read_text(encoding="utf-8")
)["package"]["version"]
TRIPLES = {
    "retok-linux-x64": ("x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl"),
    "retok-linux-aarch64": ("aarch64-unknown-linux-gnu", "aarch64-unknown-linux-musl"),
    "retok-macos-x64": ("x86_64-apple-darwin",),
    "retok-macos-arm64": ("aarch64-apple-darwin",),
    "retok-windows-x64.exe": ("x86_64-pc-windows-msvc", "x86_64-pc-windows-gnu"),
}
VOCAB_PATH = "assets/o200k_base.tiktoken"
VOCAB_URL = "https://openaipublic.blob.core.windows.net/encodings/o200k_base.tiktoken"
OPENAI_URL = "https://github.com/openai/tiktoken"
SPECIAL_MARKERS = (
    "===== Retok LICENSE =====", "===== OpenAI/tiktoken LICENSE =====",
    "===== o200k_base vocabulary provenance =====",
    "===== regex-syntax Unicode data =====", "===== unicode-ident Unicode data =====",
)
REGEX_LICENSE = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"
WINAPI_REVISION = "796a8e6c2971dc2ff1bcff166e6671284f9b5b6b"


# Reviewed, reproducible bpe-openai 0.3.1 / bpe 0.2.2 dictionary. A new
# serialization must be qualified here, never accepted from a sidecar alone.
# Generated by the authenticated upstream build.rs (no Retok build helper).
PACKED_PATH = "data/o200k_base.tiktoken.gz"
PACKED_PREFIX = bytes.fromhex("9add001553a62122232425262728292a2b2c2d2e2f303132")
PACKED_PROPERTIES = {
    "representation": "bpe-openai MessagePack BytePairEncoding",
    "source-path": PACKED_PATH,
    "source-commit": "01fa926a119793979a2ce38f8d5cae10950b7181",
    "source-compressed-sha256": "aa7f57c462db101b58b6648a2b0047128f61e68c0776814ad75251aab1bccdfa",
    "generator-build-script-sha256": "010699d4aac5a6467c4a0c0a59b4bc1696a3185f197dbc24ab6de21e1cf88e03",
    "embedded-sha256": "fc5b7cec6c587b79cdb5ac241550885e51215f997cc9f5a99d5ee7a9b25ddb8c",
    "embedded-size": "32176874",
}
PACKED_VOCAB_SHA256 = "446a9538cb6c348e3516120d7c08b09f57c36495e2acfffe59a5bf8b0cfb1a2d"
# Supplements pin archive identity and revision. MIT texts come from reviewed
# upstream files; yaml-edit uses its authenticated Apache-2.0 declaration and
# complete canonical Apache terms, with that distinct provenance made explicit.
SUPPLEMENTS = {
    ("bpe-openai", "0.3.1"): (
        "2fe75b91bfbfbdc1a56afa0dad3ea54167842aa512be25c0420704c1ad9bab3f",
        "01fa926a119793979a2ce38f8d5cae10950b7181", "https://github.com/github/rust-gems"),
    ("bpe", "0.2.2"): (
        "da14229e2f28ce0af50a65fafb87fc5f50e02cfeccfdf15037def81aed8af9e9",
        "6d4fd2ff14d384d34dc7a8280d5194788e0c7873", "https://github.com/github/rust-gems"),
    ("unsafe-libyaml", "0.2.11"): (
        "673aac59facbab8a9007c7f6108d11f63b603f7cabff99fabf650fea5c32b861",
        "a7b8d1fbd93aefbca3003dcb5fcc6a9c2297e968", "https://github.com/dtolnay/unsafe-libyaml"),
    ("yaml-edit", "0.3.1"): (
        "482be37565376de9a5502a56f19b68ecf0d4f85298ac89f3a62e03d7e4ecf9e3",
        "4cbd1d452f0bc5bbb0f92d558c30191180754c2a", "https://github.com/jelmer/yaml-edit"),
}
LIBYAML_URL = "https://github.com/yaml/libyaml/blob/2c891fc7a770e8ba2fec34fc6b545c672beb37e6/License"
GITHUB_MIT = """MIT License

Copyright (c) 2023 GitHub Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""
LIBYAML_MIT = """Copyright (c) 2017-2020 Ingy döt Net
Copyright (c) 2006-2016 Kirill Simonov

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""


# Exact bytes retrieved from the canonical URL, including the Appendix example.
# The example's placeholders are not an attribution to yaml-edit.
APACHE_2_0_URL = "https://www.apache.org/licenses/LICENSE-2.0.txt"
APACHE_2_0_SHA256 = "cfc7749b96f63bd31c3c42b5c471bf756814053e847c10f3eb003417bc523d30"
APACHE_2_0 = """
                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

   1. Definitions.

      "License" shall mean the terms and conditions for use, reproduction,
      and distribution as defined by Sections 1 through 9 of this document.

      "Licensor" shall mean the copyright owner or entity authorized by
      the copyright owner that is granting the License.

      "Legal Entity" shall mean the union of the acting entity and all
      other entities that control, are controlled by, or are under common
      control with that entity. For the purposes of this definition,
      "control" means (i) the power, direct or indirect, to cause the
      direction or management of such entity, whether by contract or
      otherwise, or (ii) ownership of fifty percent (50%) or more of the
      outstanding shares, or (iii) beneficial ownership of such entity.

      "You" (or "Your") shall mean an individual or Legal Entity
      exercising permissions granted by this License.

      "Source" form shall mean the preferred form for making modifications,
      including but not limited to software source code, documentation
      source, and configuration files.

      "Object" form shall mean any form resulting from mechanical
      transformation or translation of a Source form, including but
      not limited to compiled object code, generated documentation,
      and conversions to other media types.

      "Work" shall mean the work of authorship, whether in Source or
      Object form, made available under the License, as indicated by a
      copyright notice that is included in or attached to the work
      (an example is provided in the Appendix below).

      "Derivative Works" shall mean any work, whether in Source or Object
      form, that is based on (or derived from) the Work and for which the
      editorial revisions, annotations, elaborations, or other modifications
      represent, as a whole, an original work of authorship. For the purposes
      of this License, Derivative Works shall not include works that remain
      separable from, or merely link (or bind by name) to the interfaces of,
      the Work and Derivative Works thereof.

      "Contribution" shall mean any work of authorship, including
      the original version of the Work and any modifications or additions
      to that Work or Derivative Works thereof, that is intentionally
      submitted to Licensor for inclusion in the Work by the copyright owner
      or by an individual or Legal Entity authorized to submit on behalf of
      the copyright owner. For the purposes of this definition, "submitted"
      means any form of electronic, verbal, or written communication sent
      to the Licensor or its representatives, including but not limited to
      communication on electronic mailing lists, source code control systems,
      and issue tracking systems that are managed by, or on behalf of, the
      Licensor for the purpose of discussing and improving the Work, but
      excluding communication that is conspicuously marked or otherwise
      designated in writing by the copyright owner as "Not a Contribution."

      "Contributor" shall mean Licensor and any individual or Legal Entity
      on behalf of whom a Contribution has been received by Licensor and
      subsequently incorporated within the Work.

   2. Grant of Copyright License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      copyright license to reproduce, prepare Derivative Works of,
      publicly display, publicly perform, sublicense, and distribute the
      Work and such Derivative Works in Source or Object form.

   3. Grant of Patent License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      (except as stated in this section) patent license to make, have made,
      use, offer to sell, sell, import, and otherwise transfer the Work,
      where such license applies only to those patent claims licensable
      by such Contributor that are necessarily infringed by their
      Contribution(s) alone or by combination of their Contribution(s)
      with the Work to which such Contribution(s) was submitted. If You
      institute patent litigation against any entity (including a
      cross-claim or counterclaim in a lawsuit) alleging that the Work
      or a Contribution incorporated within the Work constitutes direct
      or contributory patent infringement, then any patent licenses
      granted to You under this License for that Work shall terminate
      as of the date such litigation is filed.

   4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:

      (a) You must give any other recipients of the Work or
          Derivative Works a copy of this License; and

      (b) You must cause any modified files to carry prominent notices
          stating that You changed the files; and

      (c) You must retain, in the Source form of any Derivative Works
          that You distribute, all copyright, patent, trademark, and
          attribution notices from the Source form of the Work,
          excluding those notices that do not pertain to any part of
          the Derivative Works; and

      (d) If the Work includes a "NOTICE" text file as part of its
          distribution, then any Derivative Works that You distribute must
          include a readable copy of the attribution notices contained
          within such NOTICE file, excluding those notices that do not
          pertain to any part of the Derivative Works, in at least one
          of the following places: within a NOTICE text file distributed
          as part of the Derivative Works; within the Source form or
          documentation, if provided along with the Derivative Works; or,
          within a display generated by the Derivative Works, if and
          wherever such third-party notices normally appear. The contents
          of the NOTICE file are for informational purposes only and
          do not modify the License. You may add Your own attribution
          notices within Derivative Works that You distribute, alongside
          or as an addendum to the NOTICE text from the Work, provided
          that such additional attribution notices cannot be construed
          as modifying the License.

      You may add Your own copyright statement to Your modifications and
      may provide additional or different license terms and conditions
      for use, reproduction, or distribution of Your modifications, or
      for any such Derivative Works as a whole, provided Your use,
      reproduction, and distribution of the Work otherwise complies with
      the conditions stated in this License.

   5. Submission of Contributions. Unless You explicitly state otherwise,
      any Contribution intentionally submitted for inclusion in the Work
      by You to the Licensor shall be under the terms and conditions of
      this License, without any additional terms or conditions.
      Notwithstanding the above, nothing herein shall supersede or modify
      the terms of any separate license agreement you may have executed
      with Licensor regarding such Contributions.

   6. Trademarks. This License does not grant permission to use the trade
      names, trademarks, service marks, or product names of the Licensor,
      except as required for reasonable and customary use in describing the
      origin of the Work and reproducing the content of the NOTICE file.

   7. Disclaimer of Warranty. Unless required by applicable law or
      agreed to in writing, Licensor provides the Work (and each
      Contributor provides its Contributions) on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
      implied, including, without limitation, any warranties or conditions
      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
      PARTICULAR PURPOSE. You are solely responsible for determining the
      appropriateness of using or redistributing the Work and assume any
      risks associated with Your exercise of permissions under this License.

   8. Limitation of Liability. In no event and under no legal theory,
      whether in tort (including negligence), contract, or otherwise,
      unless required by applicable law (such as deliberate and grossly
      negligent acts) or agreed to in writing, shall any Contributor be
      liable to You for damages, including any direct, indirect, special,
      incidental, or consequential damages of any character arising as a
      result of this License or out of the use or inability to use the
      Work (including but not limited to damages for loss of goodwill,
      work stoppage, computer failure or malfunction, or any and all
      other commercial damages or losses), even if such Contributor
      has been advised of the possibility of such damages.

   9. Accepting Warranty or Additional Liability. While redistributing
      the Work or Derivative Works thereof, You may choose to offer,
      and charge a fee for, acceptance of support, warranty, indemnity,
      or other liability obligations and/or rights consistent with this
      License. However, in accepting such obligations, You may act only
      on Your own behalf and on Your sole responsibility, not on behalf
      of any other Contributor, and only if You agree to indemnify,
      defend, and hold each Contributor harmless for any liability
      incurred by, or claims asserted against, such Contributor by reason
      of your accepting any such warranty or additional liability.

   END OF TERMS AND CONDITIONS

   APPENDIX: How to apply the Apache License to your work.

      To apply the Apache License to your work, attach the following
      boilerplate notice, with the fields enclosed by brackets "[]"
      replaced with your own identifying information. (Don't include
      the brackets!)  The text should be enclosed in the appropriate
      comment syntax for the file format. We also recommend that a
      file or class name and description of purpose be included on the
      same "printed page" as the copyright notice for easier
      identification within third-party archives.

   Copyright [yyyy] [name of copyright owner]

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
"""


def require(condition, message):
    if not condition:
        raise ValueError(message)


def sha256(path):
    with path.open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def hashes(value):
    return [{"alg": "SHA-256", "content": value}]


def properties(values):
    return [{"name": "retok:" + key, "value": value}
            for key, value in sorted(values.items())]


def property_map(component):
    entries = component.get("properties", [])
    require(isinstance(entries, list) and all(
        isinstance(p, dict) and isinstance(p.get("name"), str)
        and isinstance(p.get("value"), str) for p in entries), "invalid component properties")
    result = {p["name"]: p["value"] for p in entries}
    require(len(result) == len(entries), "duplicate component properties")
    return result


def cargo_graph(project, target):
    result = subprocess.run(
        ["cargo", "metadata", "--offline", "--locked", "--format-version", "1",
         "--filter-platform", target, "--manifest-path", str(project / "Cargo.toml")],
        check=True, capture_output=True, text=True, timeout=60,
    )
    metadata = json.loads(result.stdout)
    _, packages, _ = normal_graph(metadata)
    if any(p["name"] == "bpe-openai" for p in packages.values()):
        # metadata's flat feature union can report unused dependencies, e.g.
        # base64 as normal and zlib-rs as a build input. tree uses build contexts.
        metadata["retok-normal-graph"] = cargo_tree_graph(project, target, metadata, "normal", "retok")
        metadata["retok-generator-graph"] = cargo_tree_graph(
            project, target, metadata, "normal,build", "bpe-openai")
    return metadata


def cargo_tree_graph(project, target, metadata, kinds, package):
    result = subprocess.run(
        ["cargo", "tree", "--offline", "--locked", "--target", target,
         "--manifest-path", str(project / "Cargo.toml"), "--package", package,
         "--edges", kinds, "--prefix", "depth", "--format", "{p}", "--no-dedupe", "--color", "never"],
        check=True, capture_output=True, text=True, timeout=60,
    )
    identities = {}
    for p in metadata["packages"]:
        identities.setdefault((p["name"], p["version"]), []).append(p["id"])
    graph, stack = {}, []
    for line in result.stdout.splitlines():
        match = re.fullmatch(r"(\d+)([A-Za-z0-9_-]+) v([^ ]+)(?: .*)?", line)
        require(match, "unexpected Cargo tree output")
        depth, name, version = match.groups()
        depth = int(depth)
        keys = identities.get((name, version), [])
        require(len(keys) == 1 and depth <= len(stack), "ambiguous/invalid Cargo tree identity or depth")
        key = keys[0]
        graph.setdefault(key, set())
        if depth:
            graph[stack[depth - 1]].add(key)
        else:
            require(not stack and name == package, "unexpected Cargo tree root")
        stack[depth:] = [key]
    require(graph, "empty Cargo tree")
    return {key: sorted(deps) for key, deps in graph.items()}


def normal_graph(metadata):
    packages = {p["id"]: p for p in metadata["packages"]}
    nodes = {n["id"]: n for n in metadata["resolve"]["nodes"]}
    root = metadata["resolve"]["root"]
    require(root in packages and packages[root]["name"] == "retok"
            and packages[root]["version"] == VERSION,
            f"expected Retok {VERSION} Cargo root")
    graph = {}
    pending = [root]
    while pending:
        key = pending.pop()
        if key in graph:
            continue
        graph[key] = sorted({d["pkg"] for d in nodes[key]["deps"]
                             if any(k["kind"] is None for k in d["dep_kinds"])})
        pending.extend(graph[key])
    return root, {key: packages[key] for key in graph}, graph


def release_graph(metadata):
    """Normal runtime closure plus the vocabulary generator's build closure only."""
    root, packages, graph = normal_graph(metadata)
    if "retok-normal-graph" in metadata:
        normal_edges = metadata["retok-normal-graph"]
        graph = {key: set(deps) for key, deps in normal_edges.items()}
        for key, deps in metadata["retok-generator-graph"].items():
            graph.setdefault(key, set()).update(deps)
        all_packages = {p["id"]: p for p in metadata["packages"]}
        return (root, {key: all_packages[key] for key in graph},
                {key: sorted(deps) for key, deps in graph.items()}, set(normal_edges) - {root})
    require(not any(p["name"] == "bpe-openai" for p in packages.values()),
            "packed tokenizer requires feature-resolved Cargo trees")
    return root, packages, graph, set(packages) - {root}


def source_revision(files):
    revision = json.loads(files.get(".cargo_vcs_info.json", b"{}")).get("git", {}).get("sha1", "")
    require(re.fullmatch(r"[0-9a-f]{40}", revision), "invalid tokenizer source revision")
    return revision


def yaml_edit_license():
    """Supply canonical terms on the basis of the pinned Cargo SPDX declaration."""
    require(hashlib.sha256(APACHE_2_0.encode("utf-8")).hexdigest() == APACHE_2_0_SHA256,
            "canonical Apache license SHA-256 mismatch")
    digest, revision, repository = SUPPLEMENTS[("yaml-edit", "0.3.1")]
    return {
        "LICENSE (Apache-2.0 canonical terms)": APACHE_2_0,
        "NOTICE (Retok license provenance)": (
            "yaml-edit 0.3.1 declares Apache-2.0 in its authenticated Cargo.toml.\n"
            f"Archive SHA-256: {digest}\n"
            f"Declaration: {repository}/blob/{revision}/Cargo.toml\n"
            f"Canonical license source: {APACHE_2_0_URL}\n"
            f"Canonical license SHA-256: {APACHE_2_0_SHA256}\n"
            "The crate and reviewed revision omit a license file; these complete terms "
            "are supplied from Apache, not an upstream LICENSE file.\n"
            "No upstream NOTICE file or copyright headers were found in the reviewed "
            "crate/source tree. This provenance note is supplied by Retok.\n"
            "The canonical Appendix example is preserved verbatim and asserts no "
            "project-specific copyright attribution.\n"
        ),
    }


def supplement_texts(package, digest, files):
    identity = (package["name"], package["version"])
    expected = SUPPLEMENTS.get(identity)
    expression = "Apache-2.0" if package["name"] == "yaml-edit" else "MIT"
    require(expected and digest == expected[0] and source_revision(files) == expected[1]
            and package["license"] == expression, "unreviewed license supplement source identity")
    if package["name"] == "yaml-edit":
        return yaml_edit_license()
    _, revision, repository = expected
    url = f"{repository}/blob/{revision}/LICENSE"
    if package["name"] == "unsafe-libyaml":
        return {"NOTICE (libyaml upstream attribution)": f"Source: {LIBYAML_URL}\n\n{LIBYAML_MIT}"}
    return {"LICENSE (GitHub upstream supplement)": GITHUB_MIT,
            "NOTICE (license provenance)": f"Source: {url}\nArchive SHA-256: {digest}\n"}


def packed_source(files):
    require(PACKED_PATH in files and "build.rs" in files, "missing packed vocabulary source/build script")
    require(source_revision(files) == PACKED_PROPERTIES["source-commit"], "packed source revision mismatch")
    for path, prop in ((PACKED_PATH, "source-compressed-sha256"),
                       ("build.rs", "generator-build-script-sha256")):
        require(hashlib.sha256(files[path]).hexdigest() == PACKED_PROPERTIES[prop],
                "packed vocabulary source/build script SHA-256 mismatch")
    raw = gzip.decompress(files[PACKED_PATH])
    require(hashlib.sha256(raw).hexdigest() == PACKED_VOCAB_SHA256, "packed vocabulary source SHA-256 mismatch")
    return raw


def embedded_location(binary, prefix, size=None, digest=None):
    require(binary.stat().st_size > 0, "binary does not contain the cached o200k vocabulary")
    with binary.open("rb") as stream, mmap.mmap(stream.fileno(), 0, access=mmap.ACCESS_READ) as mapped:
        offset = mapped.find(prefix)
        require(offset >= 0, "binary does not contain the cached o200k vocabulary representation")
        if size is not None:
            require(offset + size <= len(mapped)
                    and hashlib.sha256(mapped[offset:offset + size]).hexdigest() == digest,
                    "embedded packed vocabulary SHA-256 mismatch (unreviewed representation)")
    return offset


def checked_archive(package, lock):
    """Use Cargo's local registry archive, authenticated against Cargo.lock."""
    key = (package["name"], package["version"], package["source"])
    require(key in lock and (package["source"] or "").startswith("registry+"),
            f"{key[:2]}: expected a locked registry dependency")
    digest = lock[key].get("checksum", "")
    directory = Path(package["manifest_path"]).parent
    # Cargo's registry layout: registry/src/INDEX/NAME-VERSION and cache/INDEX/*.crate.
    archive = directory.parents[1].parent / "cache" / directory.parent.name / (directory.name + ".crate")
    require(re.fullmatch(r"[0-9a-f]{64}", digest) and sha256(archive) == digest,
            f"{package['name']}: cached crate checksum differs from Cargo.lock")
    files = {}
    with tarfile.open(archive, "r:gz") as crate:
        for member in crate.getmembers():
            if not member.isfile():
                continue
            prefix = package["name"] + "-" + package["version"] + "/"
            require(member.name.startswith(prefix), "unexpected crate archive prefix")
            relative = member.name[len(prefix):]
            basename = Path(relative).name.lower()
            if (basename.startswith(("license", "licence", "copying", "notice", "unlicense"))
                    or relative in ("Cargo.toml", ".cargo_vcs_info.json", VOCAB_PATH)
                    or (package["name"] == "bpe-openai" and relative in (PACKED_PATH, "build.rs"))
                    or relative == package.get("license_file")):
                files[relative] = crate.extractfile(member).read()
    manifest = tomllib.loads(files["Cargo.toml"].decode("utf-8"))["package"]
    require(all(manifest.get(k) == package.get(k) for k in ("name", "version", "license")),
            f"{package['name']}: registry metadata differs from authenticated archive")
    return digest, files


def license_text(raw, label):
    text = raw.decode("utf-8")
    require(text.strip(), f"{label}: missing license text")
    return text


def mit_text(path, label):
    require(path is not None, f"{label}: supply a reviewed local license file")
    text = license_text(path.read_bytes(), label)
    folded = " ".join(text.lower().split())
    require(all(phrase in folded for phrase in (
        "copyright", "permission is hereby granted, free of charge",
        "the above copyright notice", 'the software is provided "as is"',
        "liability", "dealings in the software",
    )), f"{label}: expected the complete MIT license and attribution")
    return text


def section(marker, text):
    return marker + "\n" + text + ("" if text.endswith("\n") else "\n") + "\n"


def required_runtimes(target):
    names = {"rust-std"}
    if target.endswith("-linux-musl"):
        names.add("musl")
    if target.endswith("-windows-gnu"):
        names.add("mingw-w64")
    return names


def runtime_manifest(manifest, target, local=False):
    require(isinstance(manifest, dict) and set(manifest) == {"target", "components"}
            and manifest["target"] == target, "runtime manifest target/schema mismatch")
    entries = manifest["components"]
    require(isinstance(entries, list) and all(isinstance(e, dict) and isinstance(e.get("name"), str)
            for e in entries), "invalid runtime component inventory")
    names = {e["name"] for e in entries}
    required = required_runtimes(target)
    allowed = required | ({"gcc-runtime"} if target.endswith("-windows-gnu") else set())
    require(required <= names <= allowed and len(entries) == len(names), "runtime component inventory mismatch")
    for entry in entries:
        require(set(entry) == {"name", "version", "source", "license", "sha256", "notices"},
                "runtime component fields must include exact version/source/license/sha256/notices")
        require(all(isinstance(entry[k], str) and entry[k].strip() == entry[k] and entry[k]
                    for k in ("version", "source", "license", "sha256")), "missing runtime component data")
        require(re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9.+_-]*", entry["version"])
                and entry["version"].lower() not in ("latest", "stable", "nightly", "unknown"),
                "runtime version must be exact")
        require(re.fullmatch(r"https://[^\s]+", entry["source"]), "runtime source must be a public HTTPS URL")
        require(re.fullmatch(r"[0-9a-f]{64}", entry["sha256"]), "invalid runtime source/input SHA256")
        files = entry["notices"]
        value_key = "path" if local else "sha256"
        require(isinstance(files, list) and files and all(
            isinstance(f, dict) and set(f) == {"label", value_key}
            and isinstance(f["label"], str) and re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9 ._()-]*", f["label"])
            and isinstance(f[value_key], str) and f[value_key].strip()
            and (local or re.fullmatch(r"[0-9a-f]{64}", f[value_key]))
            for f in files), "runtime requires public notice labels and local paths or SHA256 hashes")
        require(len({f["label"] for f in files}) == len(files), "duplicate runtime notice label")
    return entries


def runtime_component(entry, target):
    return {"type": "library", "name": entry["name"], "version": entry["version"],
            "bom-ref": f"runtime:{entry['name']}@{entry['version']}:{target}",
            "hashes": hashes(entry["sha256"]), "licenses": [{"expression": entry["license"]}],
            "properties": properties({"source": entry["source"], "target": target,
                                      "checksum-kind": "reviewed runtime source/input SHA-256"})}


def runtime_notice_markers(entry, file):
    label = f"runtime {entry['name']} {entry['version']} {file['label']}"
    return f"===== {label} =====\n", f"\n===== END {label} =====\n"


def load_runtimes(path, target):
    entries = runtime_manifest(json.loads(path.read_bytes()), target, local=True)
    notices = ""
    for entry in sorted(entries, key=lambda e: e["name"]):
        for file in sorted(entry["notices"], key=lambda f: f["label"]):
            data = (path.parent / file.pop("path")).read_bytes()
            file["sha256"] = hashlib.sha256(data).hexdigest()
            text = license_text(data, file["label"])
            start, end = runtime_notice_markers(entry, file)
            require(start not in text and end not in text, "runtime notice contains reserved delimiter")
            notices += start + text + end
    canonical = canonical_runtime_manifest(entries, target)
    return canonical, [runtime_component(e, target) for e in entries], notices


def canonical_runtime_manifest(entries, target):
    components = [dict(e, notices=sorted(e["notices"], key=lambda f: f["label"]))
                  for e in sorted(entries, key=lambda e: e["name"])]
    return json.dumps({"target": target, "components": components}, sort_keys=True,
                      separators=(",", ":"), ensure_ascii=False)


def validate_runtimes(document, notices=None):
    root = document["metadata"]["component"]
    props = property_map(root)
    raw = props.get("retok:runtime-manifest", "")
    require(raw and hashlib.sha256(raw.encode("utf-8")).hexdigest()
            == props.get("retok:runtime-manifest-sha256"), "runtime manifest SHA256 mismatch")
    target = props["retok:target"]
    entries = runtime_manifest(json.loads(raw), target)
    require(raw == canonical_runtime_manifest(entries, target), "runtime manifest is not canonical")
    expected = sorted((runtime_component(e, target) for e in entries), key=lambda c: c["bom-ref"])
    actual = sorted((c for c in document["components"] if c["bom-ref"].startswith("runtime:")),
                    key=lambda c: c["bom-ref"])
    require(actual == expected, "runtime component inventory/data mismatch")
    edges = {e["ref"]: e["dependsOn"] for e in document["dependencies"]}
    for component in expected:
        ref = component["bom-ref"]
        require(ref in edges.get(root["bom-ref"], []) and edges.get(ref) == [],
                "runtime dependency edges mismatch")
    if notices is not None:
        for entry in entries:
            for file in entry["notices"]:
                start, end = runtime_notice_markers(entry, file)
                require(notices.count(start) == 1 and notices.count(end) == 1,
                        "missing/duplicate runtime notice marker")
                text, found, _ = notices.split(start, 1)[1].partition(end)
                require(found and text.strip() and hashlib.sha256(text.encode("utf-8")).hexdigest()
                        == file["sha256"], "runtime notice SHA256 mismatch")
    return {c["bom-ref"] for c in expected}


def effective_license(name, cargo_expression):
    if name == "regex-syntax":
        return REGEX_LICENSE
    return "MIT OR Apache-2.0" if cargo_expression == "MIT/Apache-2.0" else cargo_expression


def winapi_import_licenses(package, packages, graph, lock):
    """Offline supplement for the reviewed import archive, never unrelated crates."""
    parents = [p for p in packages.values() if p["name"] == "winapi" and p["version"] == "0.3.9"
               and package["id"] in graph[p["id"]]]
    require(len(parents) == 1, "winapi import licenses require normal-parent winapi 0.3.9")
    parent = parents[0]
    require(parent["source"] == package["source"]
            and parent["license"] == package["license"] == "MIT/Apache-2.0",
            "winapi parent source/license mismatch")
    digest, files = checked_archive(parent, lock)
    require(json.loads(files.get(".cargo_vcs_info.json", b"{}"))
            .get("git", {}).get("sha1") == WINAPI_REVISION, "winapi parent source revision mismatch")
    names = ("LICENSE-MIT", "LICENSE-APACHE")
    require(all(name in files for name in names), "winapi parent missing full license files")
    texts = {name: license_text(files[name], "winapi " + name) for name in names}
    # Reviewed root and x86_64 license files at this revision are byte-identical
    # to the two license files in the Cargo.lock-authenticated winapi archive.
    texts["NOTICE (license provenance)"] = (
        "The winapi-x86_64-pc-windows-gnu 0.4.0 package omits its license files.\n"
        "License texts supplied by Cargo.lock-authenticated winapi 0.3.9.\n"
        f"winapi archive SHA-256: {digest}\n"
        "Reviewed upstream x86_64/LICENSE-MIT and x86_64/LICENSE-APACHE match these texts.\n"
        f"Source: https://github.com/retep998/winapi-rs/tree/{WINAPI_REVISION}/x86_64\n"
    )
    return texts


def generate(project, binary, target, commit, tiktoken_license, openai_license, runtime_path):
    require(target in TRIPLES.get(binary.name, ()), "target does not match binary asset name")
    require(re.fullmatch(r"[0-9a-f]{40}|[0-9a-f]{64}", commit), "source commit must be a full Git hash")
    runtime_raw, runtimes, runtime_notices = load_runtimes(runtime_path, target)
    root, packages, graph, normal = release_graph(cargo_graph(project, target))
    lock = {(p["name"], p["version"], p.get("source")): p
            for p in tomllib.loads((project / "Cargo.lock").read_text())["package"]}
    root_ref = f"retok@{VERSION}:{target}"
    refs = {key: f"pkg:cargo/{p['name']}@{p['version']}" for key, p in packages.items()}
    refs[root] = root_ref
    require(len(set(refs.values())) == len(refs), "duplicate package identities across registries")
    notices = section(SPECIAL_MARKERS[0], license_text((project / "LICENSE").read_bytes(), "Retok"))
    components = []
    vocab = None
    for key in sorted(packages, key=lambda key: refs[key]):
        if key == root:
            continue
        package = packages[key]
        digest, files = checked_archive(package, lock)
        expression = package.get("license")
        require(isinstance(expression, str) and expression.strip(),
                f"{package['name']}: missing SPDX license expression")
        texts = {path: license_text(raw, path) for path, raw in files.items()
                 if path not in ("Cargo.toml", ".cargo_vcs_info.json", VOCAB_PATH, PACKED_PATH, "build.rs")}
        if package["name"] in ("bpe", "bpe-openai", "unsafe-libyaml", "yaml-edit"):
            texts.update(supplement_texts(package, digest, files))
        if package["name"] == "tiktoken-rs" and not texts:
            texts["LICENSE (upstream supplement)"] = mit_text(tiktoken_license, "tiktoken-rs")
        if (package["name"], package["version"]) == ("winapi-x86_64-pc-windows-gnu", "0.4.0") and not texts:
            texts = winapi_import_licenses(package, packages, graph, lock)
        require(texts, f"{package['name']}: no complete license texts in cached crate")
        marker = f"===== crate {package['name']} {package['version']} ====="
        notices += section(marker, "License expression: " + expression)
        for path, text in sorted(texts.items()):
            notices += section("--- " + path + " ---", text)
        for name, unicode_marker in (("regex-syntax", SPECIAL_MARKERS[3]),
                                     ("unicode-ident", SPECIAL_MARKERS[4])):
            if package["name"] == name:
                unicode_texts = [text for path, text in texts.items() if "unicode" in path.lower()]
                require(unicode_texts, f"{name}: missing Unicode data license")
                notices += section(unicode_marker, "\n".join(unicode_texts))
        components.append({
            "type": "library", "bom-ref": refs[key], "purl": refs[key],
            "name": package["name"], "version": package["version"],
            "hashes": hashes(digest), "licenses": [{"expression": effective_license(package["name"], expression)}],
            "properties": properties({"checksum-kind": "Cargo.lock package archive SHA-256",
                                      "source": package["source"], "cargo-license-expression": expression}),
        })
        if package["name"] in ("tiktoken-rs", "bpe-openai"):
            require(vocab is None, "multiple normal tokenizer dependencies")
            packed = package["name"] == "bpe-openai"
            if packed:
                raw = packed_source(files)
                offset = embedded_location(binary, PACKED_PREFIX,
                                           int(PACKED_PROPERTIES["embedded-size"]),
                                           PACKED_PROPERTIES["embedded-sha256"])
                embedding = dict(PACKED_PROPERTIES)
            else:
                notices += "tiktoken-rs acknowledges @spolu for the original code and .tiktoken files.\n\n"
                require(VOCAB_PATH in files, "tiktoken-rs: missing o200k vocabulary")
                raw = files[VOCAB_PATH]
                require(raw, "empty o200k vocabulary")
                offset = embedded_location(binary, raw)
                embedding = {"source-path": VOCAB_PATH, "source-commit": source_revision(files),
                             "embedded-size": str(len(raw))}
            vocab_hash = hashlib.sha256(raw).hexdigest()
            vocab_ref = "o200k_base:sha256:" + vocab_hash
            vocab = {
                "type": "data", "bom-ref": vocab_ref, "name": "o200k_base",
                "version": vocab_hash, "hashes": hashes(vocab_hash),
                "licenses": [{"expression": "MIT"}],
                "externalReferences": [{"type": "distribution", "url": VOCAB_URL},
                                       {"type": "vcs", "url": OPENAI_URL}],
                "properties": properties(dict(embedding, **{
                    "embedded-in": root_ref, "source-crate": refs[key], "embedded-offset": str(offset)})),
            }
            provenance = (f"OpenAI/tiktoken: {OPENAI_URL}\nVocabulary: {VOCAB_URL}\n"
                          f"Bundled by {refs[key]} at {embedding['source-commit']}, {embedding['source-path']}\n"
                          f"Vocabulary text SHA-256: {vocab_hash}")
            if packed:
                provenance += ("\nThe gzip source vocabulary is compiled at build time by build.rs into "
                               "bpe_o200k_base.dict (MessagePack BytePairEncoding).\n"
                               "The binary embeds this prepared representation, not the raw .tiktoken text.\n"
                               f"Embedded representation SHA-256: {embedding['embedded-sha256']}\n"
                               f"Embedded representation size: {embedding['embedded-size']} bytes\n"
                               f"Build script SHA-256: {embedding['generator-build-script-sha256']}\n"
                               f"Compressed source SHA-256: {embedding['source-compressed-sha256']}")
            notices += section(SPECIAL_MARKERS[2], provenance)
    require(vocab is not None, "normal dependency graph does not contain a supported tokenizer")
    notices += section(SPECIAL_MARKERS[1], mit_text(openai_license, "OpenAI/tiktoken"))
    notices += runtime_notices
    components.append(vocab)
    components.extend(runtimes)
    edges = [{"ref": refs[key], "dependsOn": sorted(refs[d] for d in deps)}
             for key, deps in graph.items()]
    next(e for e in edges if e["ref"] == property_map(vocab)["retok:source-crate"])["dependsOn"].append(vocab["bom-ref"])
    next(e for e in edges if e["ref"] == root_ref)["dependsOn"].extend(c["bom-ref"] for c in runtimes)
    edges.extend({"ref": c["bom-ref"], "dependsOn": []} for c in runtimes)
    for edge in edges:
        edge["dependsOn"].sort()
    edges.append({"ref": vocab["bom-ref"], "dependsOn": []})
    document = {
        "bomFormat": "CycloneDX", "specVersion": "1.5", "version": 1,
        "metadata": {"component": {
            "type": "application", "bom-ref": root_ref, "name": "retok", "version": VERSION,
            "hashes": hashes(sha256(binary)), "licenses": [{"expression": "MIT"}],
            "properties": properties({
                "target": target, "source-commit": commit,
                "cargo-lock-sha256": sha256(project / "Cargo.lock"),
                "cargo-manifest-sha256": sha256(project / "Cargo.toml"),
                "runtime-manifest": runtime_raw,
                "runtime-manifest-sha256": hashlib.sha256(runtime_raw.encode("utf-8")).hexdigest(),
                "normal-dependencies": json.dumps(sorted(refs[k] for k in normal)),
                "vocabulary-build-dependencies": json.dumps(sorted(refs[k] for k in graph if k != root and k not in normal)),
                "notices-sha256": hashlib.sha256(notices.encode("utf-8")).hexdigest(),
            }),
        }},
        "components": sorted(components, key=lambda c: c["bom-ref"]),
        "dependencies": sorted(edges, key=lambda d: d["ref"]),
    }
    validate(document, notices, binary)
    return document, notices


def component_hash(component):
    value = component.get("hashes")
    require(isinstance(value, list) and len(value) == 1 and isinstance(value[0], dict)
            and value[0].get("alg") == "SHA-256"
            and isinstance(value[0].get("content"), str)
            and re.fullmatch(r"[0-9a-f]{64}", value[0]["content"]), "missing/invalid SHA-256")
    return value[0]["content"]


def validate(document, notices, binary):
    """Validate internal inventory/bindings; this is not a signed build attestation."""
    root = document["metadata"]["component"]
    props = property_map(root)
    require(props.get("retok:target") in TRIPLES.get(binary.name, ()), "missing/mismatched root target")
    require(re.fullmatch(r"[0-9a-f]{40}|[0-9a-f]{64}", props.get("retok:source-commit", "")),
            "missing/invalid root source commit")
    require(component_hash(root) == sha256(binary), "root binary SHA-256 mismatch")
    require(props.get("retok:notices-sha256") == hashlib.sha256(notices.encode("utf-8")).hexdigest(),
            "notices SHA-256 mismatch")
    for key in ("cargo-lock-sha256", "cargo-manifest-sha256"):
        require(re.fullmatch(r"[0-9a-f]{64}", props.get("retok:" + key, "")), "missing " + key)
    components = document["components"]
    require(all(isinstance(c.get("bom-ref"), str) and c["bom-ref"] for c in [root] + components),
            "missing component reference")
    refs = {c["bom-ref"] for c in [root] + components}
    require(len(refs) == len(components) + 1, "duplicate component reference")
    runtimes = [c for c in components if c["bom-ref"].startswith("runtime:")]
    libraries = [c for c in components if c.get("type") == "library" and c not in runtimes]
    vocabularies = [c for c in components if c.get("type") == "data" and c.get("name") == "o200k_base"]
    require(len(vocabularies) == 1 and len(libraries) + len(runtimes) + 1 == len(components),
            "missing vocabulary/component inventory")
    inventory = json.loads(props.get("retok:normal-dependencies", "null"))
    build_inventory = json.loads(props.get("retok:vocabulary-build-dependencies", "[]"))
    require(isinstance(inventory, list) and isinstance(build_inventory, list)
            and all(isinstance(ref, str) for ref in inventory + build_inventory)
            and inventory == sorted(set(inventory)) and build_inventory == sorted(set(build_inventory))
            and not set(inventory) & set(build_inventory)
            and sorted(inventory + build_inventory) == sorted(c["bom-ref"] for c in libraries),
            "normal dependency inventory mismatch")
    normal_names = {c["name"] for c in libraries if c["bom-ref"] in inventory}
    require(len(normal_names & {"tiktoken-rs", "bpe-openai"}) == 1, "missing/ambiguous normal tokenizer dependency")
    require({"regex-syntax", "unicode-ident"} <= normal_names,
            "missing required normal dependency")
    for component in components:
        component_hash(component)
        licenses = component.get("licenses")
        require(isinstance(licenses, list) and len(licenses) == 1 and isinstance(licenses[0], dict)
                and isinstance(licenses[0].get("expression"), str) and licenses[0]["expression"].strip(),
                "missing component license expression")
    for library in libraries:
        declared = property_map(library).get("retok:cargo-license-expression")
        require(declared and library["licenses"] == [{"expression": effective_license(library["name"], declared)}],
                "Cargo/effective license expression mismatch")
        require(library.get("purl") == f"pkg:cargo/{library['name']}@{library['version']}"
                == library["bom-ref"], "mismatched package identity")
        marker = f"===== crate {library['name']} {library['version']} ====="
        require(notices.count(marker) == 1, "missing/duplicate dependency notice marker")
        if library["name"] in ("bpe", "bpe-openai", "unsafe-libyaml"):
            text = notices.split(marker, 1)[1].split("=====", 1)[0]
            expected = GITHUB_MIT if library["name"] != "unsafe-libyaml" else LIBYAML_MIT
            require(expected in text, "missing complete upstream license supplement")
        if library["name"] == "yaml-edit":
            expected = SUPPLEMENTS.get((library["name"], library["version"]))
            require(expected and component_hash(library) == expected[0] and declared == "Apache-2.0",
                    "unreviewed yaml-edit license source identity")
            text = notices.split(marker, 1)[1].split("=====", 1)[0]
            require(all(value in text for value in yaml_edit_license().values()),
                    "missing canonical Apache license or yaml-edit provenance")
    for marker in SPECIAL_MARKERS:
        require(marker in notices, "missing required notice marker: " + marker)
    edges = document.get("dependencies")
    require(isinstance(edges, list) and all(isinstance(e, dict) and isinstance(e.get("ref"), str)
            and isinstance(e.get("dependsOn"), list) and all(isinstance(d, str) for d in e["dependsOn"])
            for e in edges), "missing dependency relationships")
    graph = {e["ref"]: e["dependsOn"] for e in edges}
    require(len(graph) == len(edges) and set(graph) == refs
            and all(set(deps) <= refs and len(set(deps)) == len(deps) for deps in graph.values()),
            "dependency relationship inventory mismatch")
    validate_runtimes(document, notices)
    reachable, pending = set(), [root["bom-ref"]]
    while pending:
        ref = pending.pop()
        if ref not in reachable:
            reachable.add(ref)
            pending.extend(graph[ref])
    require(reachable == refs, "unreachable dependency component")
    vocab = vocabularies[0]
    vp = property_map(vocab)
    packed = "bpe-openai" in normal_names
    tokenizer = "bpe-openai" if packed else "tiktoken-rs"
    if packed:
        require(all(vp.get("retok:" + k) == v for k, v in PACKED_PROPERTIES.items())
                and component_hash(vocab) == PACKED_VOCAB_SHA256,
                "unreviewed packed vocabulary representation/provenance")
        for name in ("bpe-openai", "bpe"):
            expected = [(version, values) for (crate, version), values in SUPPLEMENTS.items() if crate == name]
            require(len(expected) == 1, "missing reviewed tokenizer identity")
            version, values = expected[0]
            matches = [c for c in libraries if c["name"] == name and c["bom-ref"] in inventory]
            require(len(matches) == 1 and matches[0]["version"] == version
                    and component_hash(matches[0]) == values[0], "unreviewed tokenizer archive identity")
    else:
        require(not build_inventory and not any("retok:" + k in vp for k in
                ("representation", "embedded-sha256", "source-compressed-sha256", "generator-build-script-sha256")),
                "legacy vocabulary representation mismatch")
    require(vp.get("retok:embedded-in") == root["bom-ref"]
            and vp.get("retok:source-path") == (PACKED_PATH if packed else VOCAB_PATH)
            and re.fullmatch(r"[0-9a-f]{40}", vp.get("retok:source-commit", ""))
            and vp.get("retok:source-crate") in {c["bom-ref"] for c in libraries if c["name"] == tokenizer}
            and vocab["bom-ref"] in graph[vp["retok:source-crate"]]
            and vocab.get("externalReferences") == [{"type": "distribution", "url": VOCAB_URL},
                                                    {"type": "vcs", "url": OPENAI_URL}],
            "missing vocabulary provenance")
    digest = component_hash(vocab)
    require(vocab["version"] == digest and vocab["bom-ref"] == "o200k_base:sha256:" + digest,
            "vocabulary hash identity mismatch")
    embedded_digest = vp["retok:embedded-sha256"] if packed else digest
    offset = int(vp.get("retok:embedded-offset", "-1"))
    size = int(vp.get("retok:embedded-size", "0"))
    require(offset >= 0 and size > 0 and offset + size <= binary.stat().st_size,
            "invalid embedded vocabulary location")
    with binary.open("rb") as stream, mmap.mmap(stream.fileno(), 0, access=mmap.ACCESS_READ) as mapped:
        require(hashlib.sha256(mapped[offset:offset + size]).hexdigest() == embedded_digest,
                "embedded vocabulary SHA-256 mismatch")


def validate_project(document, project):
    """Compare an SBOM with authoritative local inputs, without generating notices."""
    component = document["metadata"]["component"]
    props = property_map(component)
    require(props["retok:cargo-lock-sha256"] == sha256(project / "Cargo.lock")
            and props["retok:cargo-manifest-sha256"] == sha256(project / "Cargo.toml"),
            "Cargo source/lockfile hashes differ from metadata")
    root, packages, graph, normal = release_graph(cargo_graph(project, props["retok:target"]))
    refs = {key: f"pkg:cargo/{p['name']}@{p['version']}" for key, p in packages.items()}
    refs[root] = component["bom-ref"]
    runtime_refs = validate_runtimes(document)
    libraries = {c["bom-ref"]: c for c in document["components"]
                 if c["type"] == "library" and c["bom-ref"] not in runtime_refs}
    require(set(libraries) == {refs[k] for k in graph if k != root}, "Cargo dependency inventory mismatch")
    require(json.loads(props["retok:normal-dependencies"]) == sorted(refs[k] for k in normal)
            and json.loads(props.get("retok:vocabulary-build-dependencies", "[]"))
            == sorted(refs[k] for k in graph if k != root and k not in normal),
            "Cargo normal/build inventory mismatch")
    lock = {(p["name"], p["version"], p.get("source")): p
            for p in tomllib.loads((project / "Cargo.lock").read_text())["package"]}
    vocab = next(c for c in document["components"] if c["type"] == "data")
    for key, package in packages.items():
        if key == root:
            continue
        library = libraries[refs[key]]
        if package["name"] in ("tiktoken-rs", "bpe-openai"):
            digest, files = checked_archive(package, lock)
            raw = packed_source(files) if package["name"] == "bpe-openai" else files[VOCAB_PATH]
            vp = property_map(vocab)
            require(component_hash(vocab) == hashlib.sha256(raw).hexdigest()
                    and vp.get("retok:source-commit") == source_revision(files)
                    and vp.get("retok:source-crate") == refs[key], "Cargo vocabulary source mismatch")
        entry = lock[(package["name"], package["version"], package["source"])]
        require(component_hash(library) == entry["checksum"]
                and property_map(library).get("retok:cargo-license-expression") == package["license"]
                and library["licenses"] == [{"expression": effective_license(package["name"], package["license"])}],
                "Cargo package checksum/license mismatch")
    actual = {e["ref"]: set(e["dependsOn"]) for e in document["dependencies"]}
    vocab = next(c for c in document["components"] if c["type"] == "data")
    for key, deps in graph.items():
        expected = {refs[d] for d in deps}
        if key == root:
            expected.update(runtime_refs)
        if packages[key]["name"] in ("tiktoken-rs", "bpe-openai"):
            expected.add(vocab["bom-ref"])
        require(actual[refs[key]] == expected, "Cargo dependency relationships mismatch")
